file = open("fun_tell.txt","w+")
print(file.tell())
file.write("This is Tell() Function")
print(file.tell())
file.seek(0)
print(file.tell())
content = file.read()
print(content)
print(file.tell())
file.close()