file = open("fun_seek.txt","w+")
print(file.tell())
file.write("This is Seek() Function")
print(file.tell())
file.seek(0)
print(file.tell())
content = file.read()
print(content)
print(file.tell())
file.close()